"""moved shift to course, removed seat limit in course_component and moved session logic into class

Revision ID: 19410d1237ce
Revises: d32c2b5a7c00
Create Date: 2026-05-14 23:02:12.418541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "19410d1237ce"
down_revision: Union[str, Sequence[str], None] = "d32c2b5a7c00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("class_attendance_ibfk_1"), "class_attendance", type_="foreignkey"
    )
    op.drop_column("class_attendance", "class_session_id")
    op.drop_table("class_session")
    op.add_column("class", sa.Column("date", sa.DateTime(), nullable=False))
    op.add_column(
        "class", sa.Column("course_component_id", sa.BINARY(length=16), nullable=False)
    )
    op.drop_constraint(op.f("class_ibfk_1"), "class", type_="foreignkey")
    op.drop_constraint(op.f("class_ibfk_2"), "class", type_="foreignkey")
    op.create_foreign_key(
        None, "class", "course_component", ["course_component_id"], ["id"]
    )
    op.drop_column("class", "component_id")
    op.drop_column("class", "shift_type_id")
    op.add_column(
        "class_attendance", sa.Column("class_id", sa.BINARY(length=16), nullable=False)
    )
    op.create_foreign_key(None, "class_attendance", "class", ["class_id"], ["id"])
    op.add_column("course", sa.Column("shift_type_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "course", "shift_type", ["shift_type_id"], ["id"])
    op.drop_column("course_component", "seat_limit_per_class")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course_component",
        sa.Column(
            "seat_limit_per_class", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "course", type_="foreignkey")
    op.drop_column("course", "shift_type_id")
    op.add_column(
        "class_attendance",
        sa.Column("class_session_id", sa.BINARY(length=16), nullable=False),
    )
    op.drop_constraint(None, "class_attendance", type_="foreignkey")
    op.create_foreign_key(
        op.f("class_attendance_ibfk_1"),
        "class_attendance",
        "class_session",
        ["class_session_id"],
        ["id"],
    )
    op.drop_column("class_attendance", "class_id")
    op.add_column(
        "class",
        sa.Column(
            "shift_type_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "class", sa.Column("component_id", sa.BINARY(length=16), nullable=False)
    )
    op.drop_constraint(None, "class", type_="foreignkey")
    op.create_foreign_key(
        op.f("class_ibfk_2"), "class", "shift_type", ["shift_type_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("class_ibfk_1"), "class", "course_component", ["component_id"], ["id"]
    )
    op.drop_column("class", "course_component_id")
    op.drop_column("class", "date")
    op.create_table(
        "class_session",
        sa.Column("date", mysql.DATETIME(), nullable=False),
        sa.Column("class_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"], ["class.id"], name=op.f("class_session_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_as_cs",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
