"""moved log_document_request relationship from document_type to document

Revision ID: 21cc9565356a
Revises: 19410d1237ce
Create Date: 2026-05-18 21:35:45.575300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "21cc9565356a"
down_revision: Union[str, Sequence[str], None] = "19410d1237ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log_document_request",
        sa.Column("document_id", sa.BINARY(length=16), nullable=False),
    )
    op.drop_constraint(
        op.f("log_document_request_ibfk_1"), "log_document_request", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "log_document_request", "document", ["document_id"], ["id"]
    )
    op.drop_column("log_document_request", "document_type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log_document_request",
        sa.Column(
            "document_type_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "log_document_request", type_="foreignkey")
    op.create_foreign_key(
        op.f("log_document_request_ibfk_1"),
        "log_document_request",
        "document_type",
        ["document_type_id"],
        ["id"],
    )
    op.drop_column("log_document_request", "document_id")
    # ### end Alembic commands ###
