"""added columns to log_broadcast_message

Revision ID: 2c22b974ae3c
Revises: 787cfefe0deb
Create Date: 2026-05-10 16:41:56.074264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2c22b974ae3c"
down_revision: Union[str, Sequence[str], None] = "787cfefe0deb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log_broadcast_message",
        sa.Column("subject", sa.String(length=40), nullable=False),
    )
    op.add_column(
        "log_broadcast_message",
        sa.Column("document_1_file_name", sa.String(length=30), nullable=False),
    )
    op.add_column(
        "log_broadcast_message",
        sa.Column("document_2_file_name", sa.String(length=30), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log_broadcast_message", "document_2_file_name")
    op.drop_column("log_broadcast_message", "document_1_file_name")
    op.drop_column("log_broadcast_message", "subject")
    # ### end Alembic commands ###
