"""add token control columns to user

Revision ID: 380bb13a9798
Revises: 6e0614f29c17
Create Date: 2026-04-21 22:57:00.758010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "380bb13a9798"
down_revision: Union[str, Sequence[str], None] = "6e0614f29c17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password_reset_token", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "user", sa.Column("password_reset_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_reset_expires")
    op.drop_column("user", "password_reset_token")
    # ### end Alembic commands ###
