"""increase user_gender_type.description length

Revision ID: 3f6d79d22198
Revises: 21cc9565356a
Create Date: 2026-05-19 22:07:57.790387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3f6d79d22198"
down_revision: Union[str, Sequence[str], None] = "21cc9565356a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_gender_type",
        "description",
        existing_type=mysql.VARCHAR(collation="utf8mb4_0900_as_cs", length=20),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_gender_type",
        "description",
        existing_type=sa.String(length=30),
        type_=mysql.VARCHAR(collation="utf8mb4_0900_as_cs", length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
