"""alter document.base64 type to mediumtext

Revision ID: 4345e5bb85d7
Revises: 4a4d04e827bd
Create Date: 2026-05-20 23:22:28.213282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4345e5bb85d7"
down_revision: Union[str, Sequence[str], None] = "4a4d04e827bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document",
        "base64",
        existing_type=mysql.TEXT(collation="utf8mb4_0900_as_cs"),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document",
        "base64",
        existing_type=mysql.MEDIUMTEXT(),
        type_=mysql.TEXT(collation="utf8mb4_0900_as_cs"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
