"""add student_sequential column to user

Revision ID: 4a4d04e827bd
Revises: 3f6d79d22198
Create Date: 2026-05-19 22:31:56.727949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4a4d04e827bd"
down_revision: Union[str, Sequence[str], None] = "3f6d79d22198"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("student_sequential", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "user", ["student_sequential"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "student_sequential")
    # ### end Alembic commands ###
