"""Add table student_absence_justification

Revision ID: 69c1cc863039
Revises: 20d506d675d8
Create Date: 2026-05-04 23:57:48.573758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "69c1cc863039"
down_revision: Union[str, Sequence[str], None] = "20d506d675d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_absence_justification",
        sa.Column("class_attendance_id", sa.BINARY(length=16), nullable=False),
        sa.Column("document_id", sa.BINARY(length=16), nullable=True),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_attendance_id"],
            ["attendance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_absence_justification")
    # ### end Alembic commands ###
