"""remove uniqueness of user phone number

Revision ID: 735b974f478b
Revises: be2f025f18c5
Create Date: 2026-05-07 21:59:49.590496

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "735b974f478b"
down_revision: Union[str, Sequence[str], None] = "be2f025f18c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("cellphone_number"), table_name="user")
    op.drop_index(op.f("contact_cellphone_number"), table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("contact_cellphone_number"),
        "user",
        ["contact_cellphone_number"],
        unique=True,
    )
    op.create_index(op.f("cellphone_number"), "user", ["cellphone_number"], unique=True)
    # ### end Alembic commands ###
