"""Add table LegalRepresentativeDegree

Revision ID: 7807aab89438
Revises: 380bb13a9798
Create Date: 2026-04-24 21:31:54.296663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7807aab89438"
down_revision: Union[str, Sequence[str], None] = "380bb13a9798"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legal_representative_degree",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.add_column(
        "legal_representative",
        sa.Column("legal_representative_degree_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "legal_representative",
        "legal_representative_degree",
        ["legal_representative_degree_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "legal_representative", type_="foreignkey")
    op.drop_column("legal_representative", "legal_representative_degree_id")
    op.drop_table("legal_representative_degree")
    # ### end Alembic commands ###
