"""added columns to log_course_creation

Revision ID: 787cfefe0deb
Revises: 735b974f478b
Create Date: 2026-05-09 23:18:05.047385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "787cfefe0deb"
down_revision: Union[str, Sequence[str], None] = "735b974f478b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log_course_creation", sa.Column("name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "log_course_creation",
        sa.Column("total_seat_limit", sa.Integer(), nullable=False),
    )
    op.add_column(
        "log_course_creation", sa.Column("workload", sa.Integer(), nullable=False)
    )
    op.add_column(
        "log_course_creation", sa.Column("active", sa.Boolean(), nullable=False)
    )
    op.drop_constraint(
        op.f("log_course_creation_ibfk_1"), "log_course_creation", type_="foreignkey"
    )
    op.drop_column("log_course_creation", "course_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "log_course_creation",
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
    )
    op.create_foreign_key(
        op.f("log_course_creation_ibfk_1"),
        "log_course_creation",
        "course",
        ["course_id"],
        ["id"],
    )
    op.drop_column("log_course_creation", "active")
    op.drop_column("log_course_creation", "workload")
    op.drop_column("log_course_creation", "total_seat_limit")
    op.drop_column("log_course_creation", "name")
    # ### end Alembic commands ###
