"""rename table attendance to class_attendance

Revision ID: 8b1c46665fad
Revises: 69c1cc863039
Create Date: 2026-05-05 00:00:18.981825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8b1c46665fad"
down_revision: Union[str, Sequence[str], None] = "69c1cc863039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_attendance",
        sa.Column("attended", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("class_session_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_session_id"],
            ["class_session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        op.f("student_absence_justification_ibfk_1"),
        "student_absence_justification",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "student_absence_justification",
        "class_attendance",
        ["class_attendance_id"],
        ["id"],
    )
    op.drop_table("attendance")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "student_absence_justification", type_="foreignkey")
    op.create_foreign_key(
        op.f("student_absence_justification_ibfk_1"),
        "student_absence_justification",
        "attendance",
        ["class_attendance_id"],
        ["id"],
    )
    op.create_table(
        "attendance",
        sa.Column(
            "attended",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("class_session_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_session_id"], ["class_session.id"], name=op.f("attendance_ibfk_1")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("attendance_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("class_attendance")
    # ### end Alembic commands ###
