"""Initial schema

Revision ID: 8d1c6c10c941
Revises:
Create Date: 2026-05-05 01:08:32.781831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d1c6c10c941"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_type",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "document_validation_status_type",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "legal_representative_degree",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "log_application_error",
        sa.Column("exception", sa.Text(), nullable=False),
        sa.Column("stacktrace", sa.Text(), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_type",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "shift_type",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "user_gender_type",
        sa.Column("description", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "user_sex_type",
        sa.Column("description", sa.String(length=9), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "user_type",
        sa.Column("description", sa.String(length=50), nullable=False),
        sa.Column("register_user", sa.Boolean(), nullable=False),
        sa.Column("validate_user_documents", sa.Boolean(), nullable=False),
        sa.Column("list_secretaries", sa.Boolean(), nullable=False),
        sa.Column("list_educators", sa.Boolean(), nullable=False),
        sa.Column("list_students", sa.Boolean(), nullable=False),
        sa.Column("send_broadcast_message", sa.Boolean(), nullable=False),
        sa.Column("add_courses", sa.Boolean(), nullable=False),
        sa.Column("add_classes", sa.Boolean(), nullable=False),
        sa.Column("emit_user_documents", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
    )
    op.create_table(
        "user",
        sa.Column("document", sa.String(length=11), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("cellphone_number", sa.String(length=9), nullable=True),
        sa.Column("contact_cellphone_number", sa.String(length=9), nullable=True),
        sa.Column("password", sa.String(length=512), nullable=False),
        sa.Column("birthdate", sa.DateTime(), nullable=False),
        sa.Column("school", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("password_reset_token", sa.String(length=255), nullable=True),
        sa.Column("password_reset_expires", sa.DateTime(), nullable=True),
        sa.Column("sex_id", sa.Integer(), nullable=False),
        sa.Column("gender_id", sa.Integer(), nullable=False),
        sa.Column("user_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gender_id"],
            ["user_gender_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sex_id"],
            ["user_sex_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_type_id"],
            ["user_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cellphone_number"),
        sa.UniqueConstraint("contact_cellphone_number"),
        sa.UniqueConstraint("document"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "address",
        sa.Column("zip_code", sa.String(length=8), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=False),
        sa.Column("number", sa.String(length=10), nullable=False),
        sa.Column("complement", sa.String(length=100), nullable=True),
        sa.Column("neighborhood", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "course",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("total_seat_limit", sa.Integer(), nullable=False),
        sa.Column("workload", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("responsible_educator_1", sa.BINARY(length=16), nullable=False),
        sa.Column("responsible_educator_2", sa.BINARY(length=16), nullable=True),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["responsible_educator_1"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_educator_2"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "legal_representative",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("document", sa.String(length=11), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("legal_representative_degree_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["legal_representative_degree_id"],
            ["legal_representative_degree.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_broadcast_message",
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("document_1_base64", sa.Text(), nullable=False),
        sa.Column("document_2_base64", sa.Text(), nullable=False),
        sa.Column("sent_whatsapp", sa.Boolean(), nullable=False),
        sa.Column("sent_email", sa.Boolean(), nullable=False),
        sa.Column("sent_sms", sa.Boolean(), nullable=False),
        sa.Column("user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_document_request",
        sa.Column("user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("document_type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_document_validation",
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("performed_user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("performed_by_user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_report_request",
        sa.Column("report_type_id", sa.Integer(), nullable=False),
        sa.Column("user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_type_id"],
            ["report_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_user_activation",
        sa.Column("deactivation_reason", sa.String(length=500), nullable=True),
        sa.Column("activated", sa.Boolean(), nullable=False),
        sa.Column("performed_by_user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("performed_by_user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profiles_to_exclude",
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_password_history",
        sa.Column("password", sa.String(length=512), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "course_component",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("seat_limit_per_class", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "document",
        sa.Column("base64", sa.Text(), nullable=False),
        sa.Column("is_front", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("document_type_id", sa.Integer(), nullable=False),
        sa.Column("legal_representative_id", sa.BINARY(length=16), nullable=True),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_type_id"],
            ["document_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_representative_id"],
            ["legal_representative.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_course_creation",
        sa.Column("user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "log_student_enrollment",
        sa.Column("enrolled", sa.Boolean(), nullable=False),
        sa.Column("user_ip_address", sa.String(length=39), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class",
        sa.Column("seats_in_use", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("component_id", sa.BINARY(length=16), nullable=False),
        sa.Column("shift_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["course_component.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shift_type_id"],
            ["shift_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_validation",
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column("document_validation_status_type_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_validation_status_type_id"],
            ["document_validation_status_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_session",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("class_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_class",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("class_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["class.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "class_attendance",
        sa.Column("attended", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("class_session_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_session_id"],
            ["class_session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "student_absence_justification",
        sa.Column("class_attendance_id", sa.BINARY(length=16), nullable=False),
        sa.Column("document_id", sa.BINARY(length=16), nullable=True),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_attendance_id"],
            ["class_attendance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_absence_justification")
    op.drop_table("class_attendance")
    op.drop_table("user_class")
    op.drop_table("class_session")
    op.drop_table("document_validation")
    op.drop_table("class")
    op.drop_table("log_student_enrollment")
    op.drop_table("log_course_creation")
    op.drop_table("document")
    op.drop_table("course_component")
    op.drop_table("user_password_history")
    op.drop_table("profiles_to_exclude")
    op.drop_table("log_user_activation")
    op.drop_table("log_report_request")
    op.drop_table("log_document_validation")
    op.drop_table("log_document_request")
    op.drop_table("log_broadcast_message")
    op.drop_table("legal_representative")
    op.drop_table("course")
    op.drop_table("address")
    op.drop_table("user")
    op.drop_table("user_type")
    op.drop_table("user_sex_type")
    op.drop_table("user_gender_type")
    op.drop_table("shift_type")
    op.drop_table("report_type")
    op.drop_table("log_application_error")
    op.drop_table("legal_representative_degree")
    op.drop_table("document_validation_status_type")
    op.drop_table("document_type")
    # ### end Alembic commands ###
