"""removed nullability form student_absence_justification.document_id

Revision ID: a2d34a457135
Revises: 2c22b974ae3c
Create Date: 2026-05-12 00:05:18.145876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a2d34a457135"
down_revision: Union[str, Sequence[str], None] = "2c22b974ae3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_absence_justification",
        "document_id",
        existing_type=sa.BINARY(length=16),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_absence_justification",
        "document_id",
        existing_type=sa.BINARY(length=16),
        nullable=True,
    )
    # ### end Alembic commands ###
