"""Add email_verified to user

Revision ID: be2f025f18c5
Revises: 6abfa13dbf4d
Create Date: 2026-05-05 23:01:37.498702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "be2f025f18c5"
down_revision: Union[str, Sequence[str], None] = "6abfa13dbf4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_verified", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_verified")
    # ### end Alembic commands ###
