"""change enrollment to course level

Revision ID: d32c2b5a7c00
Revises: 74bc35fb66a2
Create Date: 2026-05-13 23:25:20.188181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d32c2b5a7c00"
down_revision: Union[str, Sequence[str], None] = "74bc35fb66a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_course",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user_class")
    op.add_column(
        "enrollment_waiting_list",
        sa.Column("course_id", sa.BINARY(length=16), nullable=False),
    )
    op.drop_constraint(
        op.f("enrollment_waiting_list_ibfk_1"),
        "enrollment_waiting_list",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "enrollment_waiting_list", "course", ["course_id"], ["id"]
    )
    op.drop_column("enrollment_waiting_list", "class_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enrollment_waiting_list",
        sa.Column("class_id", sa.BINARY(length=16), nullable=False),
    )
    op.drop_constraint(None, "enrollment_waiting_list", type_="foreignkey")
    op.create_foreign_key(
        op.f("enrollment_waiting_list_ibfk_1"),
        "enrollment_waiting_list",
        "class",
        ["class_id"],
        ["id"],
    )
    op.drop_column("enrollment_waiting_list", "course_id")
    op.create_table(
        "user_class",
        sa.Column(
            "active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.BINARY(length=16), nullable=False),
        sa.Column("class_id", sa.BINARY(length=16), nullable=False),
        sa.Column("id", sa.BINARY(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["class_id"], ["class.id"], name=op.f("user_class_ibfk_1")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("user_class_ibfk_2")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_as_cs",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("user_course")
    # ### end Alembic commands ###
