"""increase user phones length

Revision ID: d3ec3cf81c10
Revises: 4345e5bb85d7
Create Date: 2026-05-21 00:02:08.351849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d3ec3cf81c10"
down_revision: Union[str, Sequence[str], None] = "4345e5bb85d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "cellphone_number",
        existing_type=mysql.VARCHAR(collation="utf8mb4_0900_as_cs", length=9),
        type_=sa.String(length=11),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "contact_cellphone_number",
        existing_type=mysql.VARCHAR(collation="utf8mb4_0900_as_cs", length=9),
        type_=sa.String(length=11),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "contact_cellphone_number",
        existing_type=sa.String(length=11),
        type_=mysql.VARCHAR(collation="utf8mb4_0900_as_cs", length=9),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "cellphone_number",
        existing_type=sa.String(length=11),
        type_=mysql.VARCHAR(collation="utf8mb4_0900_as_cs", length=9),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
