"""added processed to profiles_to_exclude

Revision ID: ddd487d0a4b6
Revises: a2d34a457135
Create Date: 2026-05-12 23:15:29.978082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ddd487d0a4b6"
down_revision: Union[str, Sequence[str], None] = "a2d34a457135"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles_to_exclude", sa.Column("processed", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles_to_exclude", "processed")
    # ### end Alembic commands ###
